[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "mysql80"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 --version"]

[start]
cmd = "cd server && python3 app.py"
